#!/usr/bin/ruby

output = "// AUTOGENERATED FILE: edit 'site_configs.yml' instead and run 'build_site_configs.rb'\n"
output += "var SiteConfigs = "+`js-yaml -j #{Dir.pwd+"/background/site_configs.yml"}`.gsub(/\n/,"")+";\n"
output += "if (typeof module !== 'undefined' && module.exports) { module.exports = SiteConfigs; }\n"
File.open(Dir.pwd+"/background/site_configs.js", 'w') {|f| f.write(output) }